### PR TITLE
Infernal genome annot

### PR DESCRIPTION
**Pull request by nawrockie**
Anton, 

I've reached a good stopping point. I realize that this documentation on genome annotation is long, as I tend to add more details rather than less... I was thinking perhaps the 'Understanding Infernal Output" subsection could be its own section to reduce the length of the genome annotation section, but I'm not sure where it would go. Let me know what you think. 

Also, please have a look at what I've written and feel free to make changes. If you think that it is too detailed and have suggestions of what to cut or shorten, let me know, or just go ahead and edit it.

### CODE REVIEW

**Comment by AntonPetrov** [comment]
Thank you Eric! Will take a look first thing Monday. I am sure it's all ready to go.

**Comment by AntonPetrov** [comment]
Thank you for a great section Eric! I made a few changes in a couple of commits mostly to add hyperlinks and structure the text a bit more with bullet points and bold font so that it's easier to skim. 

I didn't know about `console` highlighting and `literalinclude`, which are both very neat tricks.

Just a couple of comments:
* The current best practice seems to remove all trailing whitespace before committing to git. In my setup I configured the text editor so that it strips trailing whitespace on each save.
* What is the `.ai` file? Is it the source for the figure? If so, that's great, I am just asking so that I know what it is.

I will merge this PR and we can continue improving the text as we go.

**Comment by nawrockie** [comment]
The .ai file is the adobe illustrator file for the trna-cmscan-alignment.png. I've just renamed it and pushed to make that more clear. Thanks for merging and cleaning it up, and for the tip on removing whitespace.

**Comment by AntonPetrov** [comment]
Great, thanks Eric! Deleting the feature branch now.

**Pull request merged**
